export const SECTIONS_MAP = {
  WELCOME: 'welcome',
  SELECT_CREATE_RECOVER: 'choose-create-recover',
  CREATE_WALLET: 'create-wallet',
  RECOVER_WALLET: 'recover-wallet',
  SELECT_CHAIN: 'select-chain',
  SEND_TOKEN: 'send-token',
  SEND_SELECT_TOKEN: 'send-select-token',
  ONBOARDING: 'onboarding',
  NFT_LIST: 'nft-list',
  NFT_COLLECTION: 'nft-collection',
  NFT_DETAIL: 'nft-detail',
  NFT_SEND: 'nft-send',
  SWAP: 'swap',
  TRANSACTIONS_LIST: 'transactions_list',
  SETTINGS: 'settings',
  LOGOUT_ALL_WALLETS: 'logout_all_wallets',
  LOGOUT_WALLET: 'logout_wallet',
};

export const EVENTS_MAP = {
  SELECT_CHAIN: 'select-chain',
  SECRET_RECOVERED: 'secret-recovered',
  SECRET_CREATED: 'secret-created',
  PASSWORD_COMPLETED: 'password-completed',
  GO_TO_MY_WALLET: 'go-to-my-wallet',
  RECOVER_COMPLETED: 'recover-completed',
  CREATION_COMPLETED: 'creation-completed',
  TOKEN_SEND_COMPLETED: 'token-send-completed',
  TOKEN_SEND_FAILED: 'token-send-failed',
  TOKEN_SEND_CANCELLED: 'token-send-cancelled',
  NFT_SEND_COMPLETED: 'nft-send-completed',
  NFT_SEND_FAILED: 'nft-send-failed',
  NFT_SEND_CANCELLED: 'nft-send-cancelled',
  NFT_LIST_COMPLETED: 'nft-list-completed',
  NFT_LIST_FAILED: 'nft-list-failed',
  NFT_LIST_CANCELLED: 'nft-list-cancelled',
  SWAP_QUOTE: 'swap-quote',
  SWAP_CONFIRMED: 'swap-confirmed',
  SWAP_COMPLETED: 'swap-compleeted',
  SWAP_FAILED: 'swap-failed',
};
